services:
    db:
        image: postgres:17.4
        shm_size: 1g
        user: postgres
        restart: always
        healthcheck:
            test: "pg_isready -U postgres --dbname=zChess"
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - 5430:5432
        environment:
            POSTGRES_USER: zero_user
            POSTGRES_DB: zChess
            POSTGRES_PASSWORD: incredible_zero
        command: >
            postgres 
            -c wal_level=logical
            -c max_wal_senders=10 
            -c max_replication_slots=5 
            -c hot_standby=on 
            -c hot_standby_feedback=on
        volumes:
            - ./init/Init-Schema.sql:/docker-entrypoint-initdb.d/Init-Schema.sql
